version: "3"

services:
  node:
    image: node:16.14
    container_name: car_shop
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MDB_URI=mongodb://mongodb:27017/CarShop
      - API_PORT=3000

  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: car_shop_net
